name : YOLO_exp
n_gpu : 1
arch:
  type: YOLOv5_BlazeFace
  args:
    anchors:
      - [20, 23, 79, 80, 105, 146, 115, 135]
      - [126, 127, 117, 147, 126, 141, 193, 193]
data_loader:
  type: FaceDataLoader
  train:
    path:  ./data/combine/train/train.txt
    imgsz: 320
    batch_size: 64
    stride: 32
    square: True
    augment: True
    workers: 16
  test:
    path: ./data/combine/test/test.txt
    imgsz: 320
    batch_size: 32
    stride: 32
    augment: False
    workers: 16
optimizer:
  type : SGD
  args:
    lr: 0.001
    momentum: 0.937
    nesterov: True
    weight_decay: 0.005

loss: LossYolov5
metrics: FaceDetectMetric
lr_scheduler:
  type: LambdaLR
  args:
    lr_lambda : ((1 + math.cos(x * math.pi / epochs)) / 2) * (1 - 0.2) + 0.2  # lrf = 0.2
trainer:
  epoch: 400
  tensorboard: True
hyp:
  momentum: 0.937
  warmup_epoch : 3
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05  # box loss gain
  cls: 0.5  # cls loss gain
  landmark: 0.005 # landmark loss gain
  cls_pw: 1.0  # cls BCELoss positive_weight
  obj: 1.0  # obj loss gain (scale with pixels)
  obj_pw: 1.0  # obj BCELoss positive_weight
  iou_t: 0.20  # IoU training threshold
  anchor_t: 4.0  # anchor-multiple threshold
  fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
  hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
  hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
  hsv_v: 0.4  # image HSV-Value augmentation (fraction)
  degrees: 0.0  # image rotation (+/- deg)
  translate: 0.1  # image translation (+/- fraction)
  scale: 0.5  # image scale (+/- gain)
  shear: 0.5  # image shear (+/- deg)
  perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
  flipud: 0.0  # image flip up-down (probability)
  fliplr: 0.5  # image flip left-right (probability)
  mosaic: 0.5  # image mosaic (probability)
  mixup: 0.0  # image mixup (probability)


